    [-2, {ammobox removeaction unlockWeaponCrate; }] call CBA_fnc_globalExecute;

ammobox addWeaponCargoGlobal["RPG7V",2];
ammobox addmagazinecargoglobal ["OG7", 6]; 
ammobox addmagazinecargoglobal ["ACE_TBG7V", 6]; 
ammobox addmagazinecargoglobal ["ACE_PG7VM", 12]; 
ammobox addweaponcargoglobal ["ACE_RPG22", 10];
ammobox addWeaponCargoGlobal["PK",2];
ammobox addmagazinecargoglobal ["100Rnd_762x54_PK", 20]; 
ammobox addWeaponCargoGlobal["Strela",2];
ammobox addmagazinecargoglobal ["Strela", 6]; 
ammobox addmagazinecargoglobal ["30Rnd_545x39_AK", 100]; 
ammobox addmagazinecargoglobal ["handgrenade_east", 50]; 
ammobox addweaponcargoglobal ["ACE_Flaregun", 2]; 
ammobox addmagazinecargoglobal ["ACE_SSRed_FG", 20]; 
ammobox addmagazinecargoglobal ["ACE_SSYellow_FG", 20]; 
ammobox addweaponcargoglobal ["NVGoggles", 2]; 
ammobox addmagazinecargoglobal ["ACE_Pomz_M", 10]; 
ammobox addmagazinecargoglobal ["ACE_MON50_M", 5]; 
ammobox addmagazinecargoglobal ["ACE_TripFlare_M", 10];
